spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
spring.datasource.username=rm562085
spring.datasource.password=140207
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.max-lifetime=240000
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.connection-timeout=30000

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.default_schema=rm562085
spring.jpa.open-in-view=false

spring.jackson.default-property-inclusion=non_null

server.port=8080

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

aquaorbital.jwt.secret=aquaorbital-secret-key-fiap-global-solution-2026-very-long-key
aquaorbital.jwt.expiration=86400000

inmet.estacao.codigo=A701
inmet.estacao.janela-dias=1
inmet.estacao.cron=0 0 1 * * *

logging.level.br.com.fiap.Phycocarbon=INFO
logging.level.org.hibernate.SQL=WARN
