version: "3.9"

networks:
  phyconet:
    driver: bridge

volumes:
  rm563197-pgdata:

services:
  rm563197-db:
    image: postgres:16-alpine
    container_name: rm563197-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: phycocarbon
      POSTGRES_USER: phycouser
      POSTGRES_PASSWORD: phycopass
    ports:
      - "5432:5432"
    volumes:
      - rm563197-pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U phycouser -d phycocarbon"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - phyconet

  rm563197-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: rm563197-app
    restart: unless-stopped
    depends_on:
      rm563197-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: azure
      APP_PORT: "8080"
      AQUAORBITAL_JWT_SECRET: aquaorbital-secret-key-fiap-global-solution-2026-very-long-key
      AQUAORBITAL_JWT_EXPIRATION: "86400000"
      INMET_ESTACAO_CODIGO: A701
      INMET_JANELA_DIAS: "1"
      INMET_CRON: "0 0 1 * * *"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/api-docs > /dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      start_period: 90s
      retries: 5
    networks:
      - phyconet
